# This workflow will tag and update the listing of a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:

  check:
    if: ${{ inputs.version != '' }}
    uses: ./.github/workflows/check.yml

  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4

    - name: Tag
      run: |
        git config user.name "GitHub Actions Release Bot"
        git config user.email "<>"
        git tag -a $VERSION -m "Release version $VERSION"
        git push origin $VERSION
      env:
        VERSION: ${{ inputs.version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Update
      run: go list -m github.com/echsylon/go-log@$VERSION
      env:
        VERSION: ${{ inputs.version }}
        GOPROXY: proxy.golang.org

